### ISSUE TITLE
How to convert private key string to public key string?

### ISSUE THREAD

**Issue by Goatghosts** [crackerli/ffi_mina_signer#1]
Hello, your library is great. But I would like to be able to convert the private key as a string to pass it to the getAddressFromSecretKey function and then retrieve the public key. 
Tell me how do I get 
B62qmQgdErTATGd8w9Bcqe8QYVUfUecBtN79Zp35Nui2dCt5VZnuUgS string 
from 
EKE5QHcQwAAaYHqTGKEtqUHVtAeaQxcAesnAsTMwm4aCVGj6TuSQ string?

**Comment by Goatghosts** [comment]
Most likely I want to get a Uint8List from a string private key and then pass it to getAddressFromSecretKey. Is it possible?

**Comment by crackerli** [comment]
Sorry for the late response, so you have solved your issue? I see this topic has been closed.
